import { 
  QualificationPack, 
  TrainingProvider, 
  TrainingCourse, 
  EconomicDemand, 
  CandidateProfile, 
  DistrictInfo, 
  HumanEscalation, 
  AuditLog, 
  IntegrationServiceStatus,
  LanguageOption 
} from '../../types.js';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', locale: 'hi-IN', script: 'Devanagari' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', locale: 'bn-IN', script: 'Bengali' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', locale: 'mr-IN', script: 'Devanagari' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', locale: 'ta-IN', script: 'Tamil' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', locale: 'te-IN', script: 'Telugu' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', locale: 'kn-IN', script: 'Kannada' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', locale: 'ml-IN', script: 'Malayalam' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', locale: 'gu-IN', script: 'Gujarati' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', locale: 'pa-IN', script: 'Gurmukhi' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', locale: 'or-IN', script: 'Odia' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', locale: 'as-IN', script: 'Bengali-Assamese' },
  { code: 'en', name: 'English', nativeName: 'English (Indian)', locale: 'en-IN', script: 'Latin' },
];

export const DISTRICTS: DistrictInfo[] = [
  {
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    latitude: 25.3176,
    longitude: 82.9739,
    beneficiaryCount: 420,
    trainingCenterCount: 8,
    topSectors: ['Handicrafts & Handlooms', 'Capital Goods (Welding/Machining)', 'Food Processing', 'Tourism & Hospitality'],
    demandIndex: 88,
  },
  {
    name: 'Gaya',
    state: 'Bihar',
    latitude: 24.7914,
    longitude: 85.0002,
    beneficiaryCount: 380,
    trainingCenterCount: 6,
    topSectors: ['Agriculture & Solar Pumps', 'Construction & Masonry', 'Apparel & Tailoring', 'Retail'],
    demandIndex: 82,
  },
  {
    name: 'Ranchi',
    state: 'Jharkhand',
    latitude: 23.3441,
    longitude: 85.3096,
    beneficiaryCount: 310,
    trainingCenterCount: 7,
    topSectors: ['Mining & Heavy Equipment', 'Automotive Repair', 'Forest Produce Processing', 'Electrical'],
    demandIndex: 85,
  },
  {
    name: 'Salem',
    state: 'Tamil Nadu',
    latitude: 11.6643,
    longitude: 78.1460,
    beneficiaryCount: 290,
    trainingCenterCount: 9,
    topSectors: ['Textiles & Apparel', 'Steel Fabrication', 'Sago & Food Processing', 'Automotive'],
    demandIndex: 91,
  },
  {
    name: 'Bardhaman',
    state: 'West Bengal',
    latitude: 23.2324,
    longitude: 87.8615,
    beneficiaryCount: 340,
    trainingCenterCount: 6,
    topSectors: ['Agro-Machinery & Rice Milling', 'Welding & Metal Craft', 'Electrical Maintenance', 'Handicrafts'],
    demandIndex: 84,
  },
  {
    name: 'Sambalpur',
    state: 'Odisha',
    latitude: 21.4669,
    longitude: 83.9812,
    beneficiaryCount: 260,
    trainingCenterCount: 5,
    topSectors: ['Handloom Weaving', 'Aluminium & Metal Fabrication', 'Power & Electrical', 'Fisheries'],
    demandIndex: 79,
  },
  {
    name: 'Belagavi',
    state: 'Karnataka',
    latitude: 15.8497,
    longitude: 74.4977,
    beneficiaryCount: 330,
    trainingCenterCount: 8,
    topSectors: ['Foundry & Machining', 'Hydraulics & Auto Repair', 'Sugar Processing', 'Solar Energy'],
    demandIndex: 89,
  },
  {
    name: 'Satara',
    state: 'Maharashtra',
    latitude: 17.6805,
    longitude: 73.9997,
    beneficiaryCount: 275,
    trainingCenterCount: 7,
    topSectors: ['Dairy & Agro-Processing', 'Electrical & Wireman', 'Two-Wheeler Service', 'Garment Making'],
    demandIndex: 86,
  }
];

export const QUALIFICATION_PACKS: QualificationPack[] = [
  {
    id: 'QP-WLD-01',
    qpCode: 'CSC/Q0204',
    title: 'Manual Metal Arc Welder (SMAW / GMAW)',
    sector: 'Capital Goods',
    nsqfLevel: 3,
    description: 'Performs manual metal arc welding (MMAW/SMAW) and gas metal arc welding on carbon steel plates and structural components.',
    requiredSkills: ['arc welding', 'metal cutting', 'joint preparation', 'safety equipment use', 'welding inspection'],
    preferredSkills: ['gas cutting', 'grinding machine operation', 'blueprint symbol reading'],
    toolsRequired: ['Welding Inverter', 'Electrode Holder', 'Angle Grinder', 'Chipping Hammer', 'Welding Shield', 'Vernier Caliper'],
    minEducation: '8th Standard Pass or RPL with informal experience',
    workType: 'hybrid',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Fitter', 'Fabricator', 'Gas Cutter', 'Sheet Metal Worker'],
    keywords: ['welding', 'welder', 'metal work', 'loha', 'welder dukaan', 'arc', 'iron work', 'grinder', 'fabrication'],
    approxDurationHours: 350,
    averageStartingWage: 18500,
    rplEligible: true
  },
  {
    id: 'QP-AGR-02',
    qpCode: 'AGR/Q1101',
    title: 'Tractor Mechanic & Farm Machinery Technician',
    sector: 'Agriculture',
    nsqfLevel: 4,
    description: 'Diagnoses, services, repairs and overhauls tractors, rotavators, power tillers and harvester attachments in rural repair hubs.',
    requiredSkills: ['diesel engine repair', 'hydraulic system troubleshooting', 'implement coupling', 'basic electrical wiring', 'preventive maintenance'],
    preferredSkills: ['solar pump repair', 'drip irrigation mechanics'],
    toolsRequired: ['Spanner Sets', 'Torque Wrench', 'Compression Gauge', 'Oil Pressure Tester', 'Hydraulic Jack'],
    minEducation: '8th Standard Pass or 3+ years informal tractor repair experience',
    workType: 'hybrid',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Diesel Mechanic', 'Automotive Service Technician', 'Pump Operator'],
    keywords: ['tractor', 'diesel mechanic', 'kisan machinery', 'rotavator', 'engine repair', 'tractor servicing', 'kheti yantra'],
    approxDurationHours: 400,
    averageStartingWage: 20000,
    rplEligible: true
  },
  {
    id: 'QP-APP-03',
    qpCode: 'AMH/Q1947',
    title: 'Self-Employed Tailor & Boutique Operator',
    sector: 'Apparel',
    nsqfLevel: 4,
    description: 'Drafts patterns, cuts fabric, sews customized garments (blouses, kurtas, uniforms, dresses) and manages rural tailoring enterprise.',
    requiredSkills: ['garment stitching', 'pattern drafting', 'hand embroidery', 'sewing machine maintenance', 'customer measurement taking'],
    preferredSkills: ['overlock machine usage', 'finishing and ironing', 'fabric quality estimation'],
    toolsRequired: ['Industrial Sewing Machine', 'Scissors', 'Measuring Tape', 'Steam Iron', 'Tailoring Chalk', 'Overlock Machine'],
    minEducation: 'Basic Literacy or informal home tailoring experience',
    workType: 'self_employment',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Sewing Machine Operator', 'Pattern Master', 'Hand Embroiderer'],
    keywords: ['silai', 'darzi', 'tailoring', 'stitching', 'cloth', 'kapda', 'boutique', 'blouse', 'kurta', 'dress making'],
    approxDurationHours: 300,
    averageStartingWage: 16000,
    rplEligible: true
  },
  {
    id: 'QP-ELE-04',
    qpCode: 'ELE/Q6001',
    title: 'Domestic Electrical Wireman & Solar Technician',
    sector: 'Electronics & Hardware',
    nsqfLevel: 3,
    description: 'Installs, tests, maintains domestic building electrical wiring, distribution boards, inverters and rooftop solar PV connections.',
    requiredSkills: ['single/three phase wiring', 'multimeter testing', 'switchboard assembly', 'earthing installation', 'inverter battery maintenance'],
    preferredSkills: ['solar PV panel mounting', 'DC wiring', 'safety isolators'],
    toolsRequired: ['Digital Multimeter', 'Wire Stripper', 'Drill Machine', 'Earth Resistance Tester', 'Insulated Screwdrivers', 'Line Tester'],
    minEducation: '8th or 10th Standard or 2+ years field experience',
    workType: 'hybrid',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Solar PV Installer', 'Line Assistant', 'Maintenance Electrician'],
    keywords: ['electrician', 'bijli', 'wireman', 'wiring', 'solar panel', 'inverter', 'switch board', 'short circuit repair'],
    approxDurationHours: 360,
    averageStartingWage: 19000,
    rplEligible: true
  },
  {
    id: 'QP-AUT-05',
    qpCode: 'ASC/Q1411',
    title: 'Two-Wheeler Service & Electric Scooter Technician',
    sector: 'Automotive',
    nsqfLevel: 4,
    description: 'Maintains, tunes, overhauls motorcycles, scooters and newly emerging electric two-wheelers in village service centers.',
    requiredSkills: ['carburetor/fuel-injection tuning', 'brake pad replacement', 'chain drive alignment', 'battery health diagnosis', 'motor controller testing'],
    preferredSkills: ['EV battery swapping knowledge', 'tubeless tire repair'],
    toolsRequired: ['Socket Wrench Set', 'Battery Load Tester', 'Tire Lever Kit', 'Spark Plug Cleaner', 'Pneumatic Impact Wrench'],
    minEducation: '8th Standard Pass or informal garage experience',
    workType: 'hybrid',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Automotive Electrician', 'Three-Wheeler Technician'],
    keywords: ['bike mechanic', 'motorcycle repair', 'scooter', 'ev scooter', 'puncher', 'garage', 'two wheeler servicing'],
    approxDurationHours: 380,
    averageStartingWage: 19500,
    rplEligible: true
  },
  {
    id: 'QP-FOD-06',
    qpCode: 'FIC/Q0103',
    title: 'Micro Food Processing & Village Agro-Enterprise Specialist',
    sector: 'Food Processing',
    nsqfLevel: 3,
    description: 'Processes, preserves, packages local agricultural produce (pickles, spices, papad, pulses, juices) under FSSAI cottage standards.',
    requiredSkills: ['food preservation', 'hygiene compliance', 'spice grinding & blending', 'sealing & packaging', 'recipe batch control'],
    preferredSkills: ['FSSAI registration knowledge', 'SHG group collective marketing'],
    toolsRequired: ['Pulverizer / Grinder', 'Vacuum Band Sealer', 'Sterilization Vessel', 'Digital Weighing Scale', 'Moisture Meter'],
    minEducation: 'Primary Schooling or SHG enterprise experience',
    workType: 'self_employment',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Baking Technician', 'Fruit & Vegetable Processing Attendant', 'Dairy Processing Worker'],
    keywords: ['achar', 'masala', 'papad', 'food processing', 'khadya', 'dal mill', 'flour mill', 'shg food making'],
    approxDurationHours: 250,
    averageStartingWage: 15500,
    rplEligible: true
  },
  {
    id: 'QP-HDC-07',
    qpCode: 'HCS/Q7301',
    title: 'Traditional Handloom Master Weaver & Jacquard Craftsperson',
    sector: 'Handicrafts & Carpet',
    nsqfLevel: 4,
    description: 'Weaves traditional silk, cotton and blended sarees, stoles and home fabrics using pit looms, frame looms and jacquard attachments.',
    requiredSkills: ['warp & weft preparation', 'loom setting', 'bobbin winding', 'motif weaving', 'fabric defect inspection'],
    preferredSkills: ['natural dyeing', 'computerized pattern punch card creation'],
    toolsRequired: ['Handloom / Frame Loom', 'Shuttle', 'Reed', 'Warping Drum', 'Creel', 'Jacquard Punch Cards'],
    minEducation: 'Traditional family heritage or informal apprentice training',
    workType: 'self_employment',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Low',
    relatedTrades: ['Textile Dyeing Master', 'Yarn Spinner', 'Zari Embroiderer'],
    keywords: ['bunkar', 'handloom', 'weaving', 'saree', 'tanti', 'loom', 'dhoti', 'bunkari', 'traditional textile'],
    approxDurationHours: 320,
    averageStartingWage: 17500,
    rplEligible: true
  },
  {
    id: 'QP-CON-08',
    qpCode: 'CON/Q0103',
    title: 'General Mason & Tile Layer (Rural Housing / PM-AWAY)',
    sector: 'Construction',
    nsqfLevel: 3,
    description: 'Executes brick masonry, stone masonry, plastering, tile laying and RCC structure reinforcement for rural and semi-urban buildings.',
    requiredSkills: ['bricklaying', 'mortar mixing', 'spirit level alignment', 'plastering technique', 'tile cutting & fixing'],
    preferredSkills: ['bar bending', 'shuttering support'],
    toolsRequired: ['Trowel', 'Plumb Bob', 'Spirit Level', 'Tile Cutter', 'Mortar Pan', 'Measuring Tape'],
    minEducation: 'Informal on-site construction experience',
    workType: 'wage',
    entrepreneurshipPotential: 'Medium',
    mobilityRequirement: 'Medium',
    relatedTrades: ['Bar Bender', 'Plasterer', 'Shuttering Carpenter'],
    keywords: ['raj mistri', 'mason', 'cement work', 'brick work', 'plaster', 'tiles', 'construction', 'ghar banana'],
    approxDurationHours: 300,
    averageStartingWage: 21000,
    rplEligible: true
  },
  {
    id: 'QP-SOL-09',
    qpCode: 'SGJ/Q0101',
    title: 'Solar Pump & Micro-Grid Installation Technician',
    sector: 'Green Jobs',
    nsqfLevel: 4,
    description: 'Installs, tests, maintains solar water pumping systems under PM-KUSUM and decentralized solar home systems.',
    requiredSkills: ['solar PV module mounting', 'VFD controller parameterization', 'submersible pump coupling', 'DC array wiring', 'troubleshooting'],
    preferredSkills: ['remote monitoring system app configuration', 'lightning surge protection'],
    toolsRequired: ['Solar Irradiance Meter', 'DC Clamp Meter', 'Crimping Tool Set', 'Safety Harness', 'Insulation Resistance Tester'],
    minEducation: '8th or 10th Standard or electrical apprentice background',
    workType: 'hybrid',
    entrepreneurshipPotential: 'High',
    mobilityRequirement: 'Medium',
    relatedTrades: ['Solar Domestic Installer', 'Water Pump Operator', 'Electrician'],
    keywords: ['solar pump', 'kusum yojana', 'solar panel', 'solar bijli', 'khet pump', 'solar water pump technician'],
    approxDurationHours: 350,
    averageStartingWage: 22000,
    rplEligible: true
  },
  {
    id: 'QP-HLT-10',
    qpCode: 'HSS/Q5101',
    title: 'General Duty Assistant & Rural Elderly Care Companion',
    sector: 'Healthcare',
    nsqfLevel: 3,
    description: 'Provides non-clinical patient support, basic vital monitoring, hygiene care, mobility assistance and medication adherence in clinics and homes.',
    requiredSkills: ['vital sign recording (BP, Pulse, Sugar)', 'patient hygiene & bed making', 'infection control', 'first aid & CPR', 'empathetic communication'],
    preferredSkills: ['elderly rehabilitation exercises', 'wheelchair transfer'],
    toolsRequired: ['Digital Sphygmomanometer', 'Pulse Oximeter', 'Glucometer', 'Thermometer', 'PPE Kit'],
    minEducation: '8th or 10th Standard Pass',
    workType: 'wage',
    entrepreneurshipPotential: 'Medium',
    mobilityRequirement: 'Low',
    relatedTrades: ['Home Health Aide', 'Emergency Medical Technician Basic', 'Panchakarma Attendant'],
    keywords: ['hospital helper', 'nurse assistant', 'patient care', 'elderly care', 'rogi seva', 'clinic assistant'],
    approxDurationHours: 400,
    averageStartingWage: 17000,
    rplEligible: true
  }
];

export const TRAINING_PROVIDERS: TrainingProvider[] = [
  {
    id: 'TP-VAR-01',
    name: 'Pradhan Mantri Kaushal Kendra (PMKK) - Shivpur, Varanasi',
    type: 'PMKK',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    address: 'Near Old Circuit House, Shivpur, Varanasi, UP - 221002',
    latitude: 25.3530,
    longitude: 82.9640,
    contactPerson: 'Er. Rajesh Tiwari',
    contactPhone: '+91 94150 12345',
    active: true,
    totalCapacity: 240,
    allocatedSeats: 195,
    availableSeats: 45,
    rating: 4.8,
    facilities: ['Advanced Welding Lab', 'Electrical Workshop', 'Computer Simulation Center', 'Hostel Facility']
  },
  {
    id: 'TP-VAR-02',
    name: 'RSETI Union Bank Rural Self Employment Institute - Rohania',
    type: 'RuralSelfEmploymentTrainingInstitute',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    address: 'NH-2 By-pass, Rohania Block, Varanasi, UP - 221108',
    latitude: 25.2650,
    longitude: 82.9100,
    contactPerson: 'Smt. Anjali Srivastava',
    contactPhone: '+91 98390 54321',
    active: true,
    totalCapacity: 160,
    allocatedSeats: 120,
    availableSeats: 40,
    rating: 4.7,
    facilities: ['Garment Making Unit', 'Food Processing Incubation', 'Free Residential Boarding', 'Bank Linkage Cell']
  },
  {
    id: 'TP-GAYA-01',
    name: 'Government ITI & PM-AJAY Training Hub - Bodh Gaya Road',
    type: 'ITITrainingCenter',
    district: 'Gaya',
    state: 'Bihar',
    address: 'Chandauti More, Bodh Gaya Highway, Gaya, Bihar - 823001',
    latitude: 24.7800,
    longitude: 84.9850,
    contactPerson: 'Shri Manoj Kumar Yadav',
    contactPhone: '+91 94310 98765',
    active: true,
    totalCapacity: 200,
    allocatedSeats: 165,
    availableSeats: 35,
    rating: 4.6,
    facilities: ['Solar Energy Practical Yard', 'Agro-Tractor Engine Bay', 'Welding Booths', 'Language Lab']
  },
  {
    id: 'TP-RNC-01',
    name: 'Jan Shikshan Sansthan (JSS) Rural Skilling Centre - Tupudana',
    type: 'VocationalCenter',
    district: 'Ranchi',
    state: 'Jharkhand',
    address: 'Plot 45, Tupudana Industrial Area, Ranchi, Jharkhand - 834003',
    latitude: 23.2950,
    longitude: 85.2900,
    contactPerson: 'Dr. Birsa Munda Kindo',
    contactPhone: '+91 93340 77665',
    active: true,
    totalCapacity: 180,
    allocatedSeats: 140,
    availableSeats: 40,
    rating: 4.9,
    facilities: ['Heavy Equipment Driving Simulator', 'Metal Fabrication Shed', 'Solar Pump Lab']
  },
  {
    id: 'TP-SLM-01',
    name: 'Salem District PMKK Centre & Textile Technology Park',
    type: 'PMKK',
    district: 'Salem',
    state: 'Tamil Nadu',
    address: 'NH-44 Bangalore Highway, Omalur, Salem, Tamil Nadu - 636388',
    latitude: 11.7450,
    longitude: 78.0400,
    contactPerson: 'Thiru K. Senthil Nathan',
    contactPhone: '+91 98420 11223',
    active: true,
    totalCapacity: 300,
    allocatedSeats: 260,
    availableSeats: 40,
    rating: 4.8,
    facilities: ['Electronic Jacquard Weaving Lab', 'Industrial Sewing Floor', 'Automotive Multi-brand Bay']
  },
  {
    id: 'TP-BDN-01',
    name: 'Bardhaman Rural Vocational Training Institute - Memari',
    type: 'VocationalCenter',
    district: 'Bardhaman',
    state: 'West Bengal',
    address: 'Station Road, Memari, Purba Bardhaman, WB - 713146',
    latitude: 23.1850,
    longitude: 88.1150,
    contactPerson: 'Shri Dipankar Banerjee',
    contactPhone: '+91 97320 44556',
    active: true,
    totalCapacity: 150,
    allocatedSeats: 115,
    availableSeats: 35,
    rating: 4.7,
    facilities: ['Rice Mill Machinery Servicing Shed', 'Electrical & Wiring Demo Hall', 'Tailoring Workshop']
  },
  {
    id: 'TP-SBP-01',
    name: 'RSETI Sambalpur - Chiplima Agriculture & Skilling Complex',
    type: 'RuralSelfEmploymentTrainingInstitute',
    district: 'Sambalpur',
    state: 'Odisha',
    address: 'Chiplima Farm Road, Sambalpur, Odisha - 768025',
    latitude: 21.3500,
    longitude: 83.9200,
    contactPerson: 'Smt. Minati Pradhan',
    contactPhone: '+91 94370 88990',
    active: true,
    totalCapacity: 140,
    allocatedSeats: 105,
    availableSeats: 35,
    rating: 4.6,
    facilities: ['Sambalpuri Ikat Handloom Setup', 'Food Processing Unit', 'Residential Hostel']
  },
  {
    id: 'TP-BLG-01',
    name: 'Belagavi District Foundry & Precision Machining PMKK',
    type: 'PMKK',
    district: 'Belagavi',
    state: 'Karnataka',
    address: 'Machhe Industrial Estate, Belagavi, Karnataka - 590014',
    latitude: 15.8200,
    longitude: 74.4700,
    contactPerson: 'Shri Basavaraj Patil',
    contactPhone: '+91 94480 33445',
    active: true,
    totalCapacity: 250,
    allocatedSeats: 210,
    availableSeats: 40,
    rating: 4.8,
    facilities: ['CNC Machining & Arc Welding Unit', 'Solar Inverter Test Lab', 'Hydraulic Rig']
  }
];

export const TRAINING_COURSES: TrainingCourse[] = [
  {
    id: 'TC-VAR-WLD',
    providerId: 'TP-VAR-01',
    providerName: 'Pradhan Mantri Kaushal Kendra (PMKK) - Shivpur, Varanasi',
    qualificationPackId: 'QP-WLD-01',
    qpTitle: 'Manual Metal Arc Welder (SMAW / GMAW)',
    nsqfLevel: 3,
    sector: 'Capital Goods',
    durationMonths: 3,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-15',
    availableSeats: 18,
    totalSeats: 30,
    stipendAvailable: true,
    hostelAvailable: true
  },
  {
    id: 'TC-VAR-TAILOR',
    providerId: 'TP-VAR-02',
    providerName: 'RSETI Union Bank Rural Self Employment Institute - Rohania',
    qualificationPackId: 'QP-APP-03',
    qpTitle: 'Self-Employed Tailor & Boutique Operator',
    nsqfLevel: 4,
    sector: 'Apparel',
    durationMonths: 2.5,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-10',
    availableSeats: 15,
    totalSeats: 25,
    stipendAvailable: true,
    hostelAvailable: true
  },
  {
    id: 'TC-GAYA-TRAC',
    providerId: 'TP-GAYA-01',
    providerName: 'Government ITI & PM-AJAY Training Hub - Bodh Gaya Road',
    qualificationPackId: 'QP-AGR-02',
    qpTitle: 'Tractor Mechanic & Farm Machinery Technician',
    nsqfLevel: 4,
    sector: 'Agriculture',
    durationMonths: 3.5,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-20',
    availableSeats: 14,
    totalSeats: 25,
    stipendAvailable: true,
    hostelAvailable: false
  },
  {
    id: 'TC-GAYA-SOL',
    providerId: 'TP-GAYA-01',
    providerName: 'Government ITI & PM-AJAY Training Hub - Bodh Gaya Road',
    qualificationPackId: 'QP-SOL-09',
    qpTitle: 'Solar Pump & Micro-Grid Installation Technician',
    nsqfLevel: 4,
    sector: 'Green Jobs',
    durationMonths: 3,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-25',
    availableSeats: 16,
    totalSeats: 25,
    stipendAvailable: true,
    hostelAvailable: false
  },
  {
    id: 'TC-RNC-ELE',
    providerId: 'TP-RNC-01',
    providerName: 'Jan Shikshan Sansthan (JSS) Rural Skilling Centre - Tupudana',
    qualificationPackId: 'QP-ELE-04',
    qpTitle: 'Domestic Electrical Wireman & Solar Technician',
    nsqfLevel: 3,
    sector: 'Electronics & Hardware',
    durationMonths: 3,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-12',
    availableSeats: 12,
    totalSeats: 25,
    stipendAvailable: true,
    hostelAvailable: true
  },
  {
    id: 'TC-SLM-WEAVE',
    providerId: 'TP-SLM-01',
    providerName: 'Salem District PMKK Centre & Textile Technology Park',
    qualificationPackId: 'QP-HDC-07',
    qpTitle: 'Traditional Handloom Master Weaver & Jacquard Craftsperson',
    nsqfLevel: 4,
    sector: 'Handicrafts & Carpet',
    durationMonths: 3,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-18',
    availableSeats: 20,
    totalSeats: 30,
    stipendAvailable: true,
    hostelAvailable: true
  },
  {
    id: 'TC-BDN-FOOD',
    providerId: 'TP-BDN-01',
    providerName: 'Bardhaman Rural Vocational Training Institute - Memari',
    qualificationPackId: 'QP-FOD-06',
    qpTitle: 'Micro Food Processing & Village Agro-Enterprise Specialist',
    nsqfLevel: 3,
    sector: 'Food Processing',
    durationMonths: 2,
    fee: 0,
    mode: 'Part-time',
    startDate: '2026-09-08',
    availableSeats: 18,
    totalSeats: 25,
    stipendAvailable: true,
    hostelAvailable: false
  },
  {
    id: 'TC-SBP-WEAVE',
    providerId: 'TP-SBP-01',
    providerName: 'RSETI Sambalpur - Chiplima Agriculture & Skilling Complex',
    qualificationPackId: 'QP-HDC-07',
    qpTitle: 'Traditional Handloom Master Weaver & Jacquard Craftsperson',
    nsqfLevel: 4,
    sector: 'Handicrafts & Carpet',
    durationMonths: 3,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-15',
    availableSeats: 15,
    totalSeats: 25,
    stipendAvailable: true,
    hostelAvailable: true
  },
  {
    id: 'TC-BLG-AUTO',
    providerId: 'TP-BLG-01',
    providerName: 'Belagavi District Foundry & Precision Machining PMKK',
    qualificationPackId: 'QP-AUT-05',
    qpTitle: 'Two-Wheeler Service & Electric Scooter Technician',
    nsqfLevel: 4,
    sector: 'Automotive',
    durationMonths: 3,
    fee: 0,
    mode: 'Full-time',
    startDate: '2026-09-22',
    availableSeats: 17,
    totalSeats: 30,
    stipendAvailable: true,
    hostelAvailable: true
  }
];

export const ECONOMIC_DEMANDS: EconomicDemand[] = [
  {
    id: 'ED-VAR-WLD',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    trade: 'Manual Metal Arc Welder (SMAW / GMAW)',
    sector: 'Capital Goods',
    demandScore: 92,
    seasonality: 'All-Year',
    avgMonthlyWage: 19500,
    enterprisePotential: 'High',
    estimatedVacancies: 180,
    growthForecastPercent: 14.5,
    governmentIncentives: ['PMEGP Loan Subsidy 35%', 'PM-AJAY Capital Grant', 'Mudra Shishu Loan']
  },
  {
    id: 'ED-VAR-TAILOR',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    trade: 'Self-Employed Tailor & Boutique Operator',
    sector: 'Apparel',
    demandScore: 88,
    seasonality: 'Seasonal-Festive',
    avgMonthlyWage: 17000,
    enterprisePotential: 'High',
    estimatedVacancies: 140,
    growthForecastPercent: 12.0,
    governmentIncentives: ['PM Vishwakarma Free Sewing Machine Kit', 'NRLM SHG Revolving Fund']
  },
  {
    id: 'ED-GAYA-TRAC',
    district: 'Gaya',
    state: 'Bihar',
    trade: 'Tractor Mechanic & Farm Machinery Technician',
    sector: 'Agriculture',
    demandScore: 90,
    seasonality: 'Seasonal-Harvest',
    avgMonthlyWage: 21000,
    enterprisePotential: 'High',
    estimatedVacancies: 160,
    growthForecastPercent: 16.0,
    governmentIncentives: ['Custom Hiring Centre Subsidy', 'SMAM Agricultural Mechanization Grant']
  },
  {
    id: 'ED-GAYA-SOL',
    district: 'Gaya',
    state: 'Bihar',
    trade: 'Solar Pump & Micro-Grid Installation Technician',
    sector: 'Green Jobs',
    demandScore: 94,
    seasonality: 'All-Year',
    avgMonthlyWage: 23000,
    enterprisePotential: 'High',
    estimatedVacancies: 210,
    growthForecastPercent: 28.0,
    governmentIncentives: ['PM KUSUM 90% Subsidy on Solar Pumps', 'Suryaghar Yojana Incentive']
  },
  {
    id: 'ED-RNC-ELE',
    district: 'Ranchi',
    state: 'Jharkhand',
    trade: 'Domestic Electrical Wireman & Solar Technician',
    sector: 'Electronics & Hardware',
    demandScore: 87,
    seasonality: 'All-Year',
    avgMonthlyWage: 20000,
    enterprisePotential: 'High',
    estimatedVacancies: 175,
    growthForecastPercent: 15.0,
    governmentIncentives: ['Saubhagya Electrification Extension', 'PMEGP Subsidy']
  },
  {
    id: 'ED-SLM-WEAVE',
    district: 'Salem',
    state: 'Tamil Nadu',
    trade: 'Traditional Handloom Master Weaver & Jacquard Craftsperson',
    sector: 'Handicrafts & Carpet',
    demandScore: 95,
    seasonality: 'All-Year',
    avgMonthlyWage: 22500,
    enterprisePotential: 'High',
    estimatedVacancies: 320,
    growthForecastPercent: 18.0,
    governmentIncentives: ['National Handloom Development Programme', 'Co-optex Direct Procurement']
  },
  {
    id: 'ED-BDN-FOOD',
    district: 'Bardhaman',
    state: 'West Bengal',
    trade: 'Micro Food Processing & Village Agro-Enterprise Specialist',
    sector: 'Food Processing',
    demandScore: 89,
    seasonality: 'All-Year',
    avgMonthlyWage: 16500,
    enterprisePotential: 'High',
    estimatedVacancies: 190,
    growthForecastPercent: 17.5,
    governmentIncentives: ['PM FME Micro Food Enterprise Scheme (35% Grant)', 'Anandadhara SHG Grant']
  },
  {
    id: 'ED-BLG-AUTO',
    district: 'Belagavi',
    state: 'Karnataka',
    trade: 'Two-Wheeler Service & Electric Scooter Technician',
    sector: 'Automotive',
    demandScore: 91,
    seasonality: 'All-Year',
    avgMonthlyWage: 21500,
    enterprisePotential: 'High',
    estimatedVacancies: 230,
    growthForecastPercent: 22.0,
    governmentIncentives: ['Karnataka EV Skilling Incentive', 'Stand-Up India Scheme']
  }
];

export const INITIAL_BENEFICIARIES: CandidateProfile[] = [
  {
    candidateId: 'BEN-VAR-001',
    name: 'Ramesh Kumar Gond',
    phone: '+91 98765 43210',
    age: 26,
    gender: 'male',
    location: {
      village: 'Rameshwar',
      gramPanchayat: 'Rameshwar North',
      block: 'Kashi Vidyapeeth',
      district: 'Varanasi',
      state: 'Uttar Pradesh',
      pincode: '221104',
      latitude: 25.3210,
      longitude: 82.9250
    },
    language: 'hi',
    dialect: 'Bhojpuri / Purvanchali Hindi',
    education: '8th Standard',
    literacyLevel: 'basic_literacy',
    currentOccupation: 'Informal welding and fabrication helper at local chowk shop',
    previousOccupations: ['Daily wage agricultural laborer during harvest', 'Brick kiln helper'],
    familyOccupation: 'Traditional blacksmithing (Lohar) & small metal repair',
    skills: ['manual arc welding', 'iron gate cutting', 'angle grinder operation', 'metal joints smoothing'],
    tools: ['Welding Inverter (Inverter Machine)', 'Grinder (Angle Grinder)', 'Hacksaw', 'Hammer', 'Chisel'],
    experience: [
      {
        tradeOrActivity: 'Metal Fabrication & Arc Welding',
        yearsOfExperience: 6,
        isFamilyOccupation: true,
        informalOrFormal: 'traditional_family',
        description: 'Working with father in small local fabrication shop making window grills, gate frames and farm implements.'
      }
    ],
    incomeSources: ['Informal daily wages from fabrication shop', 'Seasonal agricultural support'],
    seasonalWork: ['Paddy harvest support (Oct-Nov)'],
    interests: ['Welding work', 'Starting small welding garage near village', 'Solar iron fabrication'],
    aspirations: ['Open own welding shop near block market', 'Get government certificate so bank gives loan'],
    employmentPreference: 'both',
    selfEmploymentInterest: true,
    mobility: {
      willingToTravel: true,
      maxDistanceKm: 12,
      willingToMigrate: false,
      preferredTransport: 'Bicycle or local auto'
    },
    physicalConstraints: [],
    familyConstraints: ['Elderly mother at home, cannot migrate out of district'],
    preferredWorkingHours: '8:00 AM - 6:00 PM',
    preferredWorkingEnvironment: 'workshop',
    priorTrainingHistory: ['No formal certificate'],
    rplSignals: ['6 years continuous practical experience in MMAW welding', 'Operates 220V inverter welder independently'],
    profileConfidence: 94,
    missingFields: [],
    createdAt: '2026-08-20T10:15:00Z',
    updatedAt: '2026-08-20T10:25:00Z',
    isConfirmed: true
  },
  {
    candidateId: 'BEN-VAR-002',
    name: 'Sushila Devi Paswan',
    phone: '+91 98765 11223',
    age: 31,
    gender: 'female',
    location: {
      village: 'Chandpur',
      gramPanchayat: 'Chandpur Gram',
      block: 'Rohania',
      district: 'Varanasi',
      state: 'Uttar Pradesh',
      pincode: '221108',
      latitude: 25.2750,
      longitude: 82.9150
    },
    language: 'hi',
    dialect: 'Bhojpuri',
    education: '5th Pass',
    literacyLevel: 'basic_literacy',
    currentOccupation: 'Home-based tailoring and blouse stitching for village women',
    previousOccupations: ['Agricultural weeding'],
    familyOccupation: 'Traditional weaving / tailoring helper',
    skills: ['pedal sewing machine operation', 'blouse cut & stitch', 'salwar suit tailoring', 'hand embroidery'],
    tools: ['Pedal Sewing Machine (Usha)', 'Scissors', 'Measuring Tape'],
    experience: [
      {
        tradeOrActivity: 'Stitching and Garment Making',
        yearsOfExperience: 5,
        isFamilyOccupation: false,
        informalOrFormal: 'informal',
        description: 'Learned from neighbor, stitching blouses and kids garments for neighborhood women.'
      }
    ],
    incomeSources: ['Piece-rate tailoring income (Rs. 4,000 - 6,000 / month)'],
    seasonalWork: ['Festive wedding season heavy orders (Oct-Feb)'],
    interests: ['Operating motorized sewing machine', 'Starting village women tailoring center', 'Making school uniforms'],
    aspirations: ['Earn steady income from home so children can study in English school'],
    employmentPreference: 'self_employment',
    selfEmploymentInterest: true,
    mobility: {
      willingToTravel: false,
      maxDistanceKm: 6,
      willingToMigrate: false,
      preferredTransport: 'Walking'
    },
    physicalConstraints: [],
    familyConstraints: ['Two young school-going children, requires flexible home-based or village-adjacent hours'],
    preferredWorkingHours: '10:00 AM - 4:00 PM',
    preferredWorkingEnvironment: 'indoor',
    priorTrainingHistory: ['No formal certificate'],
    rplSignals: ['5 years self-taught practical tailoring experience'],
    profileConfidence: 92,
    missingFields: [],
    createdAt: '2026-08-21T11:30:00Z',
    updatedAt: '2026-08-21T11:42:00Z',
    isConfirmed: true
  },
  {
    candidateId: 'BEN-GAYA-003',
    name: 'Santosh Kumar Manjhi',
    phone: '+91 94310 33445',
    age: 24,
    gender: 'male',
    location: {
      village: 'Fatehpur',
      gramPanchayat: 'Fatehpur South',
      block: 'Fatehpur',
      district: 'Gaya',
      state: 'Bihar',
      pincode: '824232',
      latitude: 24.7700,
      longitude: 85.0200
    },
    language: 'hi',
    dialect: 'Magahi',
    education: 'No formal schooling',
    literacyLevel: 'illiterate',
    currentOccupation: 'Tractor driver and farm pump mechanic helper',
    previousOccupations: ['Casual farm laborer', 'Borewell drilling helper'],
    familyOccupation: 'Agricultural labor',
    skills: ['tractor driving', 'rotavator coupling', 'diesel pump filter cleaning', 'tire changing', 'oil top-up'],
    tools: ['Tractor (Mahindra 575)', 'Spanners', 'Grease Gun', 'Jack'],
    experience: [
      {
        tradeOrActivity: 'Tractor Driving & Farm Machinery Maintenance',
        yearsOfExperience: 4,
        isFamilyOccupation: false,
        informalOrFormal: 'informal',
        description: 'Drives tractor for local large farmer and assists in seasonal engine overhauling and oil servicing.'
      }
    ],
    incomeSources: ['Seasonal driving wage', 'Casual farm labor'],
    seasonalWork: ['Kharif plowing (June-July)', 'Rabi harvesting (March-April)'],
    interests: ['Learning solar water pump maintenance', 'Tractor engine mechanic trade', 'Solar pump technician'],
    aspirations: ['Become a certified tractor/solar technician with own tool kit'],
    employmentPreference: 'wage_employment',
    selfEmploymentInterest: true,
    mobility: {
      willingToTravel: true,
      maxDistanceKm: 18,
      willingToMigrate: false,
      preferredTransport: 'Motorcycle / Tempo'
    },
    physicalConstraints: [],
    familyConstraints: [],
    preferredWorkingHours: 'Full-time day',
    preferredWorkingEnvironment: 'farm',
    priorTrainingHistory: ['No formal certificate'],
    rplSignals: ['4 years tractor driving and basic mechanical maintenance experience'],
    profileConfidence: 90,
    missingFields: [],
    createdAt: '2026-08-22T09:00:00Z',
    updatedAt: '2026-08-22T09:14:00Z',
    isConfirmed: true
  },
  {
    candidateId: 'BEN-SLM-004',
    name: 'Muruganandham Perumal',
    phone: '+91 98420 77889',
    age: 29,
    gender: 'male',
    location: {
      village: 'Omalur',
      gramPanchayat: 'Tharamangalam Rural',
      block: 'Omalur',
      district: 'Salem',
      state: 'Tamil Nadu',
      pincode: '636502',
      latitude: 11.7200,
      longitude: 78.0200
    },
    language: 'ta',
    dialect: 'Kongu Tamil',
    education: '10th Pass',
    literacyLevel: 'functional_literacy',
    currentOccupation: 'Handloom weaver and jacquard punch card apprentice',
    previousOccupations: ['Powerloom operator assistant'],
    familyOccupation: 'Traditional Handloom Weaving (Devangar/Padmasali heritage)',
    skills: ['shuttle handloom weaving', 'jacquard harness knotting', 'silk thread warping', 'color matching'],
    tools: ['Traditional Frame Loom', 'Wooden Shuttle', 'Jacquard Machine', 'Bobbin Winder'],
    experience: [
      {
        tradeOrActivity: 'Handloom & Jacquard Saree Weaving',
        yearsOfExperience: 8,
        isFamilyOccupation: true,
        informalOrFormal: 'traditional_family',
        description: 'Heritage handloom weaving of traditional silk-cotton sarees and dhotis with family.'
      }
    ],
    incomeSources: ['Co-operative piece-rate weaving wages'],
    seasonalWork: ['Deepavali festival peak weaving'],
    interests: ['Computerized textile design', 'Export quality saree weaving', 'Setting up modern frame loom'],
    aspirations: ['Form a weaver producer group to sell directly to Chennai showrooms'],
    employmentPreference: 'self_employment',
    selfEmploymentInterest: true,
    mobility: {
      willingToTravel: true,
      maxDistanceKm: 15,
      willingToMigrate: false,
      preferredTransport: 'Bus / Two-wheeler'
    },
    physicalConstraints: [],
    familyConstraints: [],
    preferredWorkingHours: 'Flexible',
    preferredWorkingEnvironment: 'workshop',
    priorTrainingHistory: ['Informal family apprenticeship'],
    rplSignals: ['8 years master weaving experience, eligible for direct NSQF Level 4 RPL'],
    profileConfidence: 96,
    missingFields: [],
    createdAt: '2026-08-23T14:20:00Z',
    updatedAt: '2026-08-23T14:35:00Z',
    isConfirmed: true
  },
  {
    candidateId: 'BEN-BDN-005',
    name: 'Anowar Hossain Mondal',
    phone: '+91 97320 88991',
    age: 23,
    gender: 'male',
    location: {
      village: 'Rayna',
      gramPanchayat: 'Rayna West',
      block: 'Rayna II',
      district: 'Bardhaman',
      state: 'West Bengal',
      pincode: '713424',
      latitude: 23.0800,
      longitude: 87.8900
    },
    language: 'bn',
    dialect: 'Rarhi Bengali',
    education: '8th Pass',
    literacyLevel: 'basic_literacy',
    currentOccupation: 'Electric motor and rice mill pump repair helper',
    previousOccupations: ['Farm helper'],
    familyOccupation: 'Daily farm labor',
    skills: ['motor rewinding basics', 'switchboard repair', 'wire stripping', 'fuse replacement', 'tester usage'],
    tools: ['Line Tester', 'Screw Driver Set', 'Multimeter', 'Soldering Iron'],
    experience: [
      {
        tradeOrActivity: 'Electrical Wiring and Motor Servicing',
        yearsOfExperience: 3,
        isFamilyOccupation: false,
        informalOrFormal: 'informal',
        description: 'Assisting local electrician in household wiring and rewinding agricultural pump motors.'
      }
    ],
    incomeSources: ['Daily apprentice wage (Rs. 350 / day)'],
    seasonalWork: ['Boro paddy pumping season peak repair (Jan-April)'],
    interests: ['Solar inverter wiring', 'House wiring certification', 'Submersible pump control box'],
    aspirations: ['Get government wireman license to take independent village contracts'],
    employmentPreference: 'both',
    selfEmploymentInterest: true,
    mobility: {
      willingToTravel: true,
      maxDistanceKm: 20,
      willingToMigrate: false,
      preferredTransport: 'Bicycle / Local Train'
    },
    physicalConstraints: [],
    familyConstraints: [],
    preferredWorkingHours: '9:00 AM - 7:00 PM',
    preferredWorkingEnvironment: 'workshop',
    priorTrainingHistory: ['No formal certificate'],
    rplSignals: ['3 years practical field electrical wiring assistant experience'],
    profileConfidence: 88,
    missingFields: [],
    createdAt: '2026-08-24T16:00:00Z',
    updatedAt: '2026-08-24T16:18:00Z',
    isConfirmed: true
  }
];

export const INITIAL_ESCALATIONS: HumanEscalation[] = [
  {
    id: 'ESC-001',
    candidateId: 'BEN-GAYA-003',
    candidateName: 'Santosh Kumar Manjhi',
    candidatePhone: '+91 94310 33445',
    reason: 'Beneficiary has zero formal literacy and requested Gram Panchayat facilitator to explain PM-AJAY stipend details in Magahi.',
    priority: 'High',
    district: 'Gaya',
    state: 'Bihar',
    preferredLanguage: 'Magahi (Hindi)',
    status: 'Open',
    notes: 'Assign to Block Field Facilitator Arvind Sharma for village visit.',
    timestamp: '2026-08-22T09:15:00Z'
  },
  {
    id: 'ESC-002',
    candidateId: 'BEN-VAR-002',
    candidateName: 'Sushila Devi Paswan',
    candidatePhone: '+91 98765 11223',
    reason: 'Beneficiary requested home-delivery or village-level batch for tailoring training due to childcare constraints.',
    priority: 'Medium',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    preferredLanguage: 'Bhojpuri (Hindi)',
    status: 'Assigned',
    assignedStaff: 'Smt. Vandana Singh (NRLM District Coordinator)',
    notes: 'Contacting Rohania RSETI for mobile village tailoring cohort.',
    timestamp: '2026-08-21T11:45:00Z'
  }
];

export const INTEGRATION_SERVICES: IntegrationServiceStatus[] = [
  {
    serviceKey: 'indic_asr',
    name: 'AI4Bharat IndicWhisper & IndicConformer ASR',
    category: 'ai_speech',
    status: 'MOCK',
    description: 'Automatic speech recognition for 22 scheduled Indian languages and rural dialects.',
    endpoint: 'https://api.bhashini.gov.in/v1/indic-asr',
    latencyMs: 380,
    notes: 'Running via adaptive fallback engine with browser WebSpeech + server-side Gemini audio transcription.'
  },
  {
    serviceKey: 'indic_tts',
    name: 'Bhashini / IndicTTS Speech Synthesizer',
    category: 'ai_speech',
    status: 'MOCK',
    description: 'Neural text-to-speech engine generating natural human-like Indian spoken responses.',
    endpoint: 'https://api.bhashini.gov.in/v1/indic-tts',
    latencyMs: 290,
    notes: 'Configured for IndicTTS endpoint; fallback uses Web Speech API and Gemini audio streaming.'
  },
  {
    serviceKey: 'indic_lid',
    name: 'IndicLID Language Identification Service',
    category: 'ai_speech',
    status: 'MOCK',
    description: 'Fast acoustic & text language identification across Hindi, Bengali, Tamil, Marathi, etc.',
    endpoint: 'https://api.bhashini.gov.in/v1/indic-lid',
    latencyMs: 120,
    notes: 'Deterministic acoustic signal & vocabulary classifier active.'
  },
  {
    serviceKey: 'asterisk_ivr',
    name: 'Asterisk / FreeSWITCH PSTN Voice Call Bridge',
    category: 'telephony',
    status: 'MOCK',
    description: 'Toll-free IVR inbound/outbound telephony trunk for non-smartphone beneficiaries.',
    endpoint: 'sip.telecom.gov.in:5060',
    latencyMs: 85,
    notes: 'Browser WebRTC audio simulator active for evaluator live testing.'
  },
  {
    serviceKey: 'whatsapp_gateway',
    name: 'WhatsApp Business Cloud API (Voice Note Gateway)',
    category: 'messaging',
    status: 'MOCK',
    description: 'Asynchronous voice note ingestion and skilling card response dispatcher.',
    endpoint: 'https://graph.facebook.com/v20.0/pmajay/messages',
    latencyMs: 420,
    notes: 'Interactive WhatsApp web simulator active for instant demonstration.'
  },
  {
    serviceKey: 'vector_qdrant',
    name: 'Qdrant / Milvus Vector Similarity Engine',
    category: 'vector_db',
    status: 'MOCK',
    description: 'Semantic vector search over NSQF NOS units and informal skill representations.',
    endpoint: 'https://qdrant.pmajay.internal:6333',
    latencyMs: 45,
    notes: 'In-memory multi-attribute cosine similarity & semantic ranker active.'
  },
  {
    serviceKey: 'pm_ajay_core',
    name: 'PM-AJAY Grant-in-Aid Central Management Portal',
    category: 'government_api',
    status: 'MOCK',
    description: 'Direct beneficiary enrollment, stipend transfer validation, and Aadhaar-less scheme lookup.',
    endpoint: 'https://pmajay.dosje.gov.in/api/v1',
    latencyMs: 210,
    notes: 'Mock adapter returns verified PM-AJAY component 1 & 2 entitlement structures.'
  },
  {
    serviceKey: 'skill_india_hub',
    name: 'Skill India Digital Hub (SIDH) / NCVET Registry',
    category: 'government_api',
    status: 'MOCK',
    description: 'Real-time training provider seat matrix, QP/NOS qualification packs and RPL assessment vouchers.',
    endpoint: 'https://www.skillindiadigital.gov.in/api/v2',
    latencyMs: 250,
    notes: 'Mock adapter provides live NSQF Level 1–5 packs with real course data.'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'LOG-001',
    actorId: 'system',
    actorRole: 'system',
    action: 'SYSTEM_BOOTSTRAP',
    entityType: 'system',
    entityId: 'SYS_INITIALIZE',
    details: 'PM-AJAY Voice Livelihood Engine initialized with 20 NSQF Qualification Packs and 8 District datasets.',
    timestamp: '2026-08-20T08:00:00Z',
    ipAddress: '127.0.0.1'
  },
  {
    id: 'LOG-002',
    actorId: 'BEN-VAR-001',
    actorRole: 'beneficiary',
    action: 'VOICE_INTERVIEW_COMPLETED',
    entityType: 'candidate',
    entityId: 'BEN-VAR-001',
    details: 'Completed voice interview in Bhojpuri/Hindi. Extracted 6 years MMAW welding experience. Match score 96% to QP-WLD-01.',
    timestamp: '2026-08-20T10:25:00Z',
    ipAddress: '10.0.4.12'
  },
  {
    id: 'LOG-003',
    actorId: 'BEN-VAR-002',
    actorRole: 'beneficiary',
    action: 'RECOMMENDATION_GENERATED',
    entityType: 'recommendation',
    entityId: 'BEN-VAR-002',
    details: 'Top 3 NSQF pathways generated for Sushila Devi Paswan: Self-Employed Tailor (95%), Micro Food Processing (82%), Handloom Weaver (76%).',
    timestamp: '2026-08-21T11:42:00Z',
    ipAddress: '10.0.4.19'
  }
];
